apiVersion: 0.1
openapi: 3.0.3
info:
  title: QED Temp Schools API - OpenAPI 3.0
  description: 'This is a temporary API that contains mock data related to QED'
  termsOfService: http://swagger.io/terms/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '0.1'
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:7230/api/
  - url: http://localhost:5084/api/
tags:
  - name: school
    description: Operations related to schools
    externalDocs:
      description: Find out more
      url: http://swagger.io 
paths:
  /schools/:
    get:
      tags:
        - school
      summary: Get all schools
      description: Returns a list of schools. For more information, click on https://jamatya.github.io/ .
      operationId: getAllSchools
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'
            application/xml:  
              schema:
                $ref: '#/components/schemas/School'
        '404':
          description: Schools not found
  /schools/{id}:
    get:
      tags:
        - school
      summary: Find school by ID
      description: Returns a single school
      operationId: getSchoolById
      parameters:
        - name: id
          in: path
          description: ID of the school to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/School'          
            application/xml:
              schema:
                $ref: '#/components/schemas/School'
        '400':
          description: Invalid ID supplied
        '404':
          description: School not found
components:
  schemas:
    School:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Sherwood State School
        type:
          type: string
          example: Public 
        ranking:
          type: integer
          format: int64
          example: 3
      
    
