apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jdoe  
spec:
  profile:
    displayName: Jane Doe
    email: jane-doe@example.com
    picture: https://example.com/staff/jane-with-party-hat.jpeg
  memberOf: [dp-team]
